from __future__ import annotations

from typing import Any, Protocol


class SportAdapter(Protocol):
    sport_name: str

    def getEvents(self, **kwargs) -> list[dict[str, Any]]: ...

    def getHistoricalEvents(self, **kwargs) -> list[dict[str, Any]]: ...

    def getOdds(self, **kwargs) -> list[dict[str, Any]]: ...

    def getStats(self, event_id: int) -> dict[str, Any] | None: ...

    def normalizeEvent(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def runPrediction(self, event_id: int, **kwargs) -> dict[str, Any]: ...

    def runBacktest(self, **kwargs) -> dict[str, Any]: ...

